
#
# default route for 404 error handling
#

-
  name:  'Frontend'
  uriPattern: '<FrontendSubRoutes>'
  defaults:
    '@package':    'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    'node':
      handler:     'TechDivision\NotFound\Routing\NodeNotFoundRoutePartHandler'
  subRoutes:
    'FrontendSubRoutes':
      package: 'TYPO3.Neos'
      suffix:  'Frontend'
      variables:
        'defaultUriSuffix': ''